import pandas as pd

from .stats import calcCollevStats


class filterCollev:
    """
    Select Collective events that last longer than coll_duration
    and have a larger total size than coll_total_size

    Args
    ----
    data: pandas dataframe
        dataframe with detected collective events

    frame_column: str
        string indicating the frame column in data

    collid_column: str
        string indicating the collective event id column in data

    Methods
    -------
    filter(): public method
        returns filtered pandas dataframe
    """

    def __init__(
        self,
        data: pd.DataFrame,
        frame_column: str = "time",
        collid_column: str = "collid",
    ):
        self.data = data
        self.frame_column = frame_column
        self.collid_column = collid_column

    def _filter_collev(
        self,
        data: pd.DataFrame,
        collev_duration: pd.DataFrame,
        collev_id,
        min_duration,
        min_size,
    ):
        """
        Uses the dataframe generated by self._get_collev_duration()
        to filter collective events that last longer than
        min_duration and are larger than min_size

        Args
        ----
        data: pandas dataframe
            dataframe containing unfiltered collective events

        collev_id: str
            string indicating the contained collective id column

        min_duration: int
            minimal duration of a collective event for it to be returned

        min_size: int
            minimal size for a collective event to be returned

        Returns:
        --------
            Dataframe containing filtered collective events

        """
        collev_duration = collev_duration[
            (collev_duration["duration"] >= min_duration) & (collev_duration["tot_size"] >= min_size)
        ]
        data = data[data[collev_id].isin(collev_duration[collev_id])]
        return data

    def filter(self, coll_duration: int = 9, coll_total_size: int = 10):
        """
        Filter and return collective events
        according to the parameters specified in the object instance

        Args
        ----
        coll_duration: int
            minimal duration of collective events to be selected

        coll_total_size: int
            minimal total size of collective events to be selected

        Returns
        -------
        Returns pandas dataframe containing filtered collective events
        """
        colev_duration = calcCollevStats().calculate(self.data, self.frame_column, self.collid_column)

        filtered_df = self._filter_collev(
            self.data,
            colev_duration,
            self.collid_column,
            coll_duration,
            coll_total_size,
        )
        return filtered_df


if __name__ == "__main__":
    test_data = pd.read_csv("/home/benjamingraedel/Documents/arcos_data.csv")
    filtered_data = filterCollev(data=test_data, frame_column="time", collid_column="collid").filter(
        coll_duration=9, coll_total_size=10
    )
    print(filtered_data)
